#ifndef ENUMS_H
#define ENUMS_H

typedef enum  {
    OPCODE_ADD,
    OPCODE_SUB,
    OPCODE_MUL,
    OPCODE_DIV,
    OPCODE_LT,
    OPCODE_LTE,
    OPCODE_GT,
    OPCODE_GTE,
    OPCODE_EQ,
    OPCODE_NOT,
    OPCODE_AND,
    OPCODE_OR,
    OPCODE_XOR,
    OPCODE_ASR,
    OPCODE_LSL,
    OPCODE_LSR,
    OPCODE_LOAD,
    OPCODE_STORE,
    OPCODE_ASSIGN,
    OPCODE_LABEL,
    OPCODE_JUMP,
    OPCODE_BRANCH,
    OPCODE_HALT,
    OPCODE_PHI,
    // AST Leaf Opcodes
    OPCODE_IMMEDIATE,
    OPCODE_REGISTER,
    OPCODE_MEMORY_ADDRESS,
} IROpcode;


#endif // ENUMS_H
